// autogenerated file
class Stmt {
    constructor(ini) {
        Object.assign(this, ini);
    }
    accept(visitor) {}
}
module.exports = {
Expression: class extends Stmt {
    accept(visitor) {
        return visitor.visitExpressionStmt(this);
    }
},
Print: class extends Stmt {
    accept(visitor) {
        return visitor.visitPrintStmt(this);
    }
},
Var: class extends Stmt {
    accept(visitor) {
        return visitor.visitVarStmt(this);
    }
},
Block: class extends Stmt {
    accept(visitor) {
        return visitor.visitBlockStmt(this);
    }
}
}