const fs = require('fs');
const path = require('path');

function defineAST(outputDir, baseName, types) {
    const filePath = path.join(outputDir, `${baseName}.js`);
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    fs.writeFileSync(filePath, `// autogenerated file
class ${baseName} {
    constructor(ini) {
        Object.assign(this, ini);
    }
    accept(visitor) {}
}
module.exports = {
${types.map(x => ({ name: x, baseName })).map(defineType).join(',\n')}
}`);
}

function defineType({ name, baseName }) {
    return `${name}: class extends ${baseName} {
    accept(visitor) {
        return visitor.visit${name}${baseName}(this);
    }
}`;
}

module.exports = defineAST;